CREATE TABLE IF NOT EXISTS events (
    event_id TEXT PRIMARY KEY,
    announcement_date TEXT,
    event_date TEXT,
    year INTEGER,
    company_tier TEXT,
    company TEXT,
    event_group TEXT,
    event_type TEXT,
    evidence_text TEXT,
    commodity_group TEXT,
    commodity_subcategory TEXT,
    asset_name TEXT,
    asset_type TEXT,
    value_chain TEXT,
    value_chain_link TEXT,
    region TEXT,
    country TEXT,
    counterparty TEXT,
    deal_value TEXT,
    deal_currency TEXT,
    deal_status TEXT,
    source_url TEXT,
    source_title TEXT,
    source_type TEXT,
    confidence_score REAL,
    needs_review TEXT,
    created_at TEXT,
    updated_at TEXT,
    deal_value_numeric REAL,
    deal_value_is_minimum BOOLEAN,
    loaded_at TEXT
);
